---
title: "A Quantitative Assessment of Resource Allocation Efficiency in China: 2003–2022"
collection: portfolio
excerpt: "**Abstract:** China’s productivity growth has slowed over the past 15 years, a period during which structural transformation has accelerated. The varying pace and nature of this shift across provinces raise questions of how resource allocation—both sectoral and regional— shapes aggregate productivity dynamics. To explore this issue, this paper first compiles a province-sector dataset spanning 2003–22, based on official statistics with key adjustments to ensure internal consistency. We then apply the standard accounting framework to estimate marginal products for each province-sector. Our findings reveal a substantial decline in the dispersion of marginal products across provinces and sectors, indicating improved resource allocation efficiency. Significant declines are also observed in the within-province dispersion of marginal products across sectors and the cross-province dispersion of marginal products in services, whereas the secondary industry exhibits the opposite trend. Finally, we construct a model incorporating non-homothetic preferences, CES aggregators of sectoral inputs, and inter-regional trade to quantitatively evaluate the implications of these changes for resource allocation efficiency. Changes in the dispersion of marginal products have played a significant role in driving aggregate TFP growth in the past. Addressing current allocation inefficiencies holds the potential to substantially enhance aggregate TFP growth in the future."
---

This is a joint work with Guangyu Pei and Zheng (Michael) Song.

**Abstract:** China’s productivity growth has slowed over the past 15 years, a period during which structural transformation has accelerated. The varying pace and nature of this shift across provinces raise questions of how resource allocation—both sectoral and regional— shapes aggregate productivity dynamics. To explore this issue, this paper first compiles a province-sector dataset spanning 2003–22, based on official statistics with key adjustments to ensure internal consistency. We then apply the standard accounting framework to estimate marginal products for each province-sector. Our findings reveal a substantial decline in the dispersion of marginal products across provinces and sectors, indicating improved resource allocation efficiency. Significant declines are also observed in the within-province dispersion of marginal products across sectors and the cross-province dispersion of marginal products in services, whereas the secondary industry exhibits the opposite trend. Finally, we construct a model incorporating non-homothetic preferences, CES aggregators of sectoral inputs, and inter-regional trade to quantitatively evaluate the implications of these changes for resource allocation efficiency. Changes in the dispersion of marginal products have played a significant role in driving aggregate TFP growth in the past. Addressing current allocation inefficiencies holds the potential to substantially enhance aggregate TFP growth in the future.
